demoscene/static/css/pages/show_scener.less
Under 800px width the whole thing is unreadably squashed anyway
=> Fix scener page for mobiles

homepage/templates/homepage/home.html
Fixes the issue where 'by' is left trailing an non-existent author.
=> Checks for byline_string on the homepage production results.

demoscene/utils/groklinks.py
Add a new Modland mirror, located in Antarctica.
When I was trying to add the Antarctica link in a production like [this](https://demozoo.org/music/169898/), Demozoo considered the download link as generic.
See also: http://modland.com/mirrors.txt
=> Add Antarctica mirror to the list

demoscene/utils/groklinks.py
Originally discussed via Slack, this website currently displays "Parked" placeholder page. This pull request archives these links so they are not shown in production page nor edited (by normal user?)
Thanks.
=> Archive AsciiArena links

demoscene/tasks.py, demozoo/__init__.py, demozoo/celery.py, demozoo/settings/base.py, demozoo/settings/test.py, etc/demozoo-celery-supervisor.conf, etc/demozoo-celerybeat-supervisor.conf, janeway/tasks.py, pouet/tasks.py, productions/tasks.py, requirements-production.txt, requirements.txt, sceneorg/tasks.py, screenshots/tasks.py
Prerequisite to upgrading to celery 4.x, which we need to upgrade from python 3.6: https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html
=> remove djcelery in favour of celery's own django integration

demozoo/settings/base.py, pouet/management/commands/fetch_pouet_data.py, pouet/matching.py, pouet/tests/test_commands.py
Hopefully stop it hammering the CPU so much every two weeks...
* use the data dumps at https://data.pouet.net/ instead of hitting the Pouet API for every known group
* Optimise matching queries: cache the 'get pouet-valid prod types' query between requests, and simplify the 'fetch this releaser's prods' by prefetching nick IDs and prod type IDs and using a raw query with subselects instead of joins
=> Optimise Pouet data fetches

maintenance/forms.py, maintenance/reports.py, maintenance/tests/test_views.py, maintenance/views.py, src/style/_legacy/components/production_listing_filters.scss
Also add a 'release year' filter to the other filterable "prods without X" reports.
This is mostly so that I can get Pouet cross-links for 2021 releases as complete as possible for the benefit of the Meteoriks (and rule out the possibility that there's a hidden gem that only exists on Demozoo that everyone misses because they're only looking at Pouet data)
=> Add 'prods without Pouet links' report

lib/fuzzy_date.py, requirements-production.txt, requirements.txt
Currently we are using an ancient version (2.5.1) of python-dateutil for date parsing, because newer versions broke the parser so that it can't simultaneously parse European dd/mm/yyyy dates and ISO YYYY-MM-DD dates. This prevents us from upgrading past Python 3.9.
Since this shows no sign of being fixed any time soon, switch to europarse, our shiny new fork of the last good version of dateutil.parser updated for current Python versions: https://github.com/demozoo/europarse
=> Switch to europarse for date parsing

demoscene/tests/test_groklinks.py, demoscene/utils/groklinks.py
If the `v` parameter of a regular Youtube link contains multiple slashes (for example, someone has pasted another URL after it) this will dutifully be saved to the database as the parameter. However, since we represent timestamped links as `<video_id>/<timestamp>`, unpacking it again (to output the URL) will lead to it trying to split on slashes, and that code doesn't account for the possibility of more than one slash. Fix this by properly rejecting video IDs with invalid characters in them.
=> Reject youtube video IDs with invalid characters

src/style/_legacy/pages/home.scss
Quick band-aid to prevent large non-breaking text from peeping outside of a comment's container. The reported case was a rather generous archive.org url.
A more flexible/robust solution would be to offer markdown in comments, like elsewhere in the site. This is a separate discussion though.
=> add band-aid to avoid large urls breaking layout

parties/templates/parties/edit_organiser_protected.html, parties/tests/test_party_views.py, parties/views/parties.py
Close the loophole where party organiser credits for a locked scener can still be edited from the party page.
=> Prevent editing party organiser credits for a locked scener via the party page

package.json, search/templates/search/search.html, src/style/_legacy/assets/search.scss
Regression bug found by vitalkanev on the search page -the inline button was always visible instead of just in the scenario where javascript was disabled/unsupported. It also didn't look very well, so this fixes the look ever so slightly.
Bumps Demozoo to 1.1.1
=> fixes button appearance when javascript is absent

bbs/templates/bbs/_tags.html, bbs/templates/bbs/_text_ads.html, bbs/templates/bbs/show.html, bbs/tests/test_views.py, bbs/views.py, demoscene/templates/groups/show.html, demoscene/templates/sceners/show.html, demoscene/templatetags/releaser_tags.py, demoscene/tests/test_releaser_views.py, demoscene/views/groups.py, demoscene/views/releasers.py, demoscene/views/sceners.py, demozoo/templates/shared/credited_production_listing.html, parties/templates/parties/show.html, parties/templates/parties/show_series.html, parties/tests/test_party_views.py, parties/views/parties.py, productions/carousel.py, productions/templates/productions/_award_recommendations.html, productions/templates/productions/_credits.html, productions/templates/productions/_downloads.html, productions/templates/productions/_external_links.html, productions/templates/productions/_info_files.html, productions/templates/productions/_notes.html, productions/templates/productions/_tags.html, productions/templates/productions/show.html, productions/tests/test_production_views.py, productions/views/generic.py, productions/views/productions.py
Following our plan to reduce the UI clutter of edit buttons: hide them all from non-logged-in users, except for one at the top.
Currently only implemented on the production page - others to follow.
=> Remove secondary edit buttons from non-logged-in users

.docker/web/Dockerfile, .docker/web/entrypoint
This PR removes nodejs/npm steps in the demozoo-web container config. 
They aren't functionally doing what they're supposed to be doing and cause confusion about the completeness of this step.
Right now the workaround for running the CSS/SVG build steps when using Docker is to run these steps on the host system.
=> Remove nodejs steps from docker config

demoscene/utils/groklinks.py
Recognizes link to Plus4World that are of the /profile/<slug> form instead of /members. Unsure how profile and member differ
=> Recognize Plus4World Profile links

bbs/urls.py, bbs/views.py, common/views.py, demoscene/shortcuts.py, demoscene/tests/test_scener_views.py, demoscene/urls.py, demoscene/views/groups.py, demoscene/views/releasers.py, demoscene/views/sceners.py, parties/tests/test_party_views.py, parties/urls.py, parties/views/parties.py, productions/urls.py, productions/views/productions.py, users/urls.py, users/views/accounts.py
Replace the `simple_ajax_form` helper with some generic class-based views to reduce code duplication
=> Add generic class-based view for editing forms

maintenance/templates/maintenance/duplicate_production_external_links.html, maintenance/templates/maintenance/duplicate_releaser_external_links.html, maintenance/tests/test_views.py, maintenance/views.py
Ref: #410
Split the duplicate external links report into separate reports for productions and releasers, and rewrite the main query to perform a `GROUP BY` on the link class/parameter rather than joining the table against itself. In efficiency terms it's now essentially finding duplicates in an ordered list rather than an unordered one...
The production report now completes in around 5 seconds on my local machine, which may be borderline for working without crashing on the live site, but that's down from over 100 seconds, so worth trying out at least :-)
=> Optimise duplicate external links report

common/templates/base.html, demoscene/management/commands/dump_ai_corpus.py, etc/demozoo-productionvm-nginx.conf, etc/demozoo-staging-nginx.conf, etc/nepenthes-supervisor.conf, users/templates/registration/login.html
Demozoo has been getting a lot of bot traffic, including some particularly bad offenders that make tens/hundreds of requests per second, ignore robots.txt, use fake untrackable user agents and use a wide IP block to evade rate limiting. Add a [nepenthes](https://zadzmo.org/code/nepenthes/) honeypot (disallowed by robots.txt to keep out legitimate bots such as Google) to hopefully tie up their resources and keep them off the real site.
=> Set up nepenthes honeypot for AI crawlers

demoscene/static/js/editable_grid.js, demoscene/static/js/results_table.js
An annoyance that has probably been around for ages, but I only just discovered it when switching from Chrome to Firefox: if you have a cell of the results table highlighted (but not actively in edit mode) and start typing, the first character will switch you to edit mode on Firefox but that character will not actually be entered into the input box.
This is because we relied on an apparently Chrome-specific quirk: if you set the focus to another element during a keypress event handler, and don't cancel the event by returning false, the newly-focused element will receive the keypress and process it as normal. This isn't the case on Firefox - to get around this, we move the event handler to the keydown event (and use `event.key.length === 1` to identify keypresses corresponding to printable …
=> Stop first character of input in compo results table from being swallowed up on Firefox

demoscene/static/js/lightbox.js, demoscene/templates/groups/show.html, demoscene/templates/sceners/show.html, productions/forms.py, productions/templates/productions/edit_links.html, productions/templates/productions/includes/downloads_panel.html, productions/views/productions.py, src/style/assets/_form.scss
Rebase of @jensadne 's PR #351 with some tweaks:
* Only applies to download links for now - I think external links will need a different kind of UI where the description comes into play only after we've failed to match the link against a recognised type (and thus it takes the place of the 'WWW' label)
* Added extra margin between sub-forms of the download links form, to make it clearer which fields are grouped together
* Modified the behaviour of the "focus the first empty field" mode of the lightbox so that it looks for the first sub-form whose first visible field is empty (which in this case will be the place to paste in a new URL, rather than the empty description field of the first existing link).
I'm still a little wary that some people will use the field for editorialising about the …
=> Download link descriptions
