demozoo/demozoo

- productions/static/productions/css/pages/show_production.less
> Responsive prod page

- demoscene/static/js/demozoo.js
Speeds up searching process considerably.
> Turn autocomplete list into actual links to allow middle clicking

- demoscene/static/css/page_base.less
- templates/base.html
- templates/registration/login.html
> Aesthetic tweaks (SceneID PR)

- README.md
host where manage.py is missing exec bit
fixes #239
> added 2 lines to clarify running manage.py on Windows 

- demoscene/static/css/assets/_icon.less
- demoscene/static/css/assets/_list.less
- demoscene/static/css/assets/_panel.less
- demoscene/static/css/layout.less
- platforms/static/platforms/css/pages/platform-overview.less
- platforms/static/platforms/css/pages/show_platform.less
- platforms/templates/platforms/show.html
Lotek reported this one -some glitches in productions layout adressed.
> Visual glitches in productions remedied.

- demoscene/static/css/assets/_button.less
- demoscene/static/css/assets/_icon.less
- demoscene/static/css/assets/_panel.less
- demoscene/static/css/layout.less
- platforms/templates/platforms/show.html
Quick stab at the low-hanging fruit of ticket 254, without any of the niceties of a nice SVG icon solution. That's pretty much tied up at the moment, this ought to suffice for now.
> Ticket 254

- demoscene/utils/groklinks.py
> Detect ModArchive Lite Links

- productions/static/productions/css/components/carousel.less
- productions/static/productions/js/components/carousel.js
This should be an end to the weird (mostly firefox) artefacts in mosaic tiles.
There were some lines better not crossed with relation to the size and scaling of non-mosiac images -
-that warrants more discussion, so it's best to open new tickets for that :)
> Screenshots mosaic updated

- demoscene/utils/groklinks.py
e.g. https://demozoo.org/productions/193458/
(this PR is untested, like all my other groklinks.py PRs ;)
> Detect csdb links that contain index.php

- demoscene/utils/groklinks.py
does what it says on the tin (hopefully!)
> update canonical link formats for some websites to HTTPS

- bbs/models.py
> add EHQ as a BBS affiliation type

- bbs/templates/bbs/show_text_ad.html
- bbs/views.py
- maintenance/templates/maintenance/fix_text_file_encoding.html
- maintenance/views.py
- parties/templates/parties/results_file.html
- parties/views/parties.py
- productions/templates/productions/show_info_file.html
- productions/views/productions.py
> Keep track of return URL on fix-encoding view.

- productions/models.py
- productions/templates/productions/show.html
- productions/tests/test_models.py
> Include correct production type and release date in meta description

- src/style/utility/mixin/_markdown.scss
@glennlunder was kind enough to give footnotes a whirl and we found that the layout was still a bit lacking. This PR should make things look a bit prettier!
> Add some sugar on footnotes

- productions/models.py
- productions/templates/productions/_core_details.html
- productions/tests/test_models.py
- src/style/_legacy/assets/_signpost.scss
> Linkify prod type boxes to link to prod listings

- maintenance/management/commands/newcomers_report.py
- maintenance/tests/test_commands.py
A report (available via command line only) listing all releasers who released their first production (in a Meteoriks-qualifying category) in the given year.
> Meteoriks new talent report

- homepage/templates/homepage/home.html
- homepage/tests/test_home_view.py
- homepage/views/home.py
- parties/models.py
- parties/tests/test_models.py
- src/style/_legacy/pages/home.scss
Now shows past parties from the current month, or last month if today's date is before the 15th.
Fixes #359
> Replace "Upcoming parties" with "Party calendar"

- productions/tests/test_production_views.py
- productions/views/productions.py
fixes half of #375 (scener lookups for credits still todo)
> Allow looking up productions by ID or URL

- api/serializers.py
> Add external links to parties API endpoint

- homepage/models.py
- homepage/templates/homepage/home.html
- homepage/templates/homepage/news/_news_story.html
- homepage/templates/homepage/news/index.html
- homepage/tests/test_news_views.py
- homepage/urls.py
- homepage/views/news.py
- src/style/_legacy/pages/home.scss
> News archive section

- bbs/models.py
- bbs/templates/bbs/show.html
- bbs/views.py
- comments/urls.py
- comments/views.py
- homepage/templates/homepage/home.html
- maintenance/templates/maintenance/prod_comments.html
- parties/models.py
> Comments for BBSes

- maintenance/reports.py
- maintenance/views.py
Baed off the FilteredProdutionsReport functionality.
> New reports for prods without external links and prods without release date

- bbs/views.py
- productions/models.py
Sort nicks using lower case comparison (as requested in Discord)
> Fix sorting order of credits

- maintenance/views.py
As requested in https://github.com/demozoo/demozoo/issues/24
Additionally, added curly brackets as well as < brackets.
Reveals some interesing group names :-)
> Added square, curly brackets and < brackets to the query
